services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vpn-tg-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      ADMINS_FILE: /data/admins.json
      USERS_FILE: /data/users.json
    volumes:
      - bot-data:/data

volumes:
  bot-data:
